apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-userprofile-deployment
  labels:
    app: tripinsights-userprofile-deployment
spec:
  selector:
    matchLabels:
      app: tripinsights-userprofile
  template:
    metadata:
      labels:
        app: tripinsights-userprofile
    spec:
      containers:                  
      - name: tripinsights-userprofile
        image: registrydtm0276.azurecr.io/tripinsights/userprofile:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/secrets"
          readOnly: true                    
        ports:
          - containerPort: 80
      volumes:
      - name: secrets-store01-inline
        csi: 
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-user-msi"            