apiVersion: v1
kind: Service
metadata:
  name: tripinsights-poi-deployment
  labels:
    run: tripinsights-poi-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: tripinsights-poi-deployment